### ISSUE TITLE
15 errors

### ISSUE THREAD

**Issue by Theo-denBlanken** [RekCus/Formulieren-PRO1#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/RekCus/Formulieren-PRO1/blob/master/

Feedback: bij validatie[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by RekCus** [comment]
Fixed
