### ISSUE TITLE
geen values

### ISSUE THREAD

**Issue by Theo-denBlanken** [RekCus/Formulieren-PRO1#10]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c

        <input type="checkbox" name="G-Peeken">Peeken
		<input type="checkbox" name="G-Defenden">Defenden
		<input type="checkbox" name="G-Rushen">Rushen
		<input type="checkbox" name="G-Attacken">Attacken
		<input type="checkbox" name="G-Killen">Killen 
```

URL: https://github.com/RekCus/Formulieren-PRO1/blob/master/formulieren/index.html

Feedback: dus krijg je onbetekende gegevens in je verwerkng. In dit geval 'on'[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"e809bf63f6c68e9da67ed1509071964ae4982b32","path":"formulieren/index.html","reviewer":"Theo-denBlanken"}')

**Comment by RekCus** [comment]
toegevoegd
