### ISSUE TITLE
autofocus toevoegen

### ISSUE THREAD

**Issue by Theo-denBlanken** [RekCus/Formulieren-PRO1#6]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/RekCus/Formulieren-PRO1/blob/master/formulieren/index.html

Feedback: meestel de eerste input[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"1dc013eed4ffab55f33821bfa1391826d0a91b76","path":"formulieren/index.html","reviewer":"Theo-denBlanken"}')

**Comment by RekCus** [comment]
Gedaan
